version: '3.3'
services:
  oauthbridge:
    image: samuelecat/oauthbridge:latest
    container_name: oauthbridge
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile
    volumes:
      - ./conf:/etc/oauthbridge
    ports:
      - "8081:8081"
      - "9999:9999"
      - "9001:9001"
